#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/zavudev/sdk-go,github.com/stainless-sdks/zavudev-go"

echo "==> Building zavudev"
go build ./cmd/zavudev
